# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controll.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_controll_ui(object):
    def setupUi(self, controll_ui):
        controll_ui.setObjectName("controll_ui")
        controll_ui.resize(915, 553)
        self.btn_onsite_ready = QtWidgets.QPushButton(controll_ui)
        self.btn_onsite_ready.setGeometry(QtCore.QRect(310, 400, 141, 27))
        self.btn_onsite_ready.setObjectName("btn_onsite_ready")
        self.line = QtWidgets.QFrame(controll_ui)
        self.line.setGeometry(QtCore.QRect(420, 30, 71, 541))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_onsite_remove = QtWidgets.QPushButton(controll_ui)
        self.btn_onsite_remove.setGeometry(QtCore.QRect(310, 100, 97, 27))
        self.btn_onsite_remove.setObjectName("btn_onsite_remove")
        self.btn_onsite_reset = QtWidgets.QPushButton(controll_ui)
        self.btn_onsite_reset.setGeometry(QtCore.QRect(310, 480, 97, 27))
        self.btn_onsite_reset.setObjectName("btn_onsite_reset")
        self.btn_online_ready = QtWidgets.QPushButton(controll_ui)
        self.btn_online_ready.setGeometry(QtCore.QRect(760, 400, 141, 27))
        self.btn_online_ready.setObjectName("btn_online_ready")
        self.btn_online_reset = QtWidgets.QPushButton(controll_ui)
        self.btn_online_reset.setGeometry(QtCore.QRect(760, 480, 97, 27))
        self.btn_online_reset.setObjectName("btn_online_reset")
        self.btn_online_remove = QtWidgets.QPushButton(controll_ui)
        self.btn_online_remove.setGeometry(QtCore.QRect(760, 90, 97, 27))
        self.btn_online_remove.setObjectName("btn_online_remove")
        self.label = QtWidgets.QLabel(controll_ui)
        self.label.setGeometry(QtCore.QRect(70, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(controll_ui)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(controll_ui)
        self.line_2.setGeometry(QtCore.QRect(-20, 360, 971, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.txtf_onsite_add = QtWidgets.QPlainTextEdit(controll_ui)
        self.txtf_onsite_add.setGeometry(QtCore.QRect(140, 380, 161, 71))
        self.txtf_onsite_add.setObjectName("txtf_onsite_add")
        self.txtf_online_add = QtWidgets.QPlainTextEdit(controll_ui)
        self.txtf_online_add.setGeometry(QtCore.QRect(590, 380, 151, 71))
        self.txtf_online_add.setObjectName("txtf_online_add")
        self.online_list_view = QtWidgets.QListWidget(controll_ui)
        self.online_list_view.setGeometry(QtCore.QRect(590, 70, 151, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.online_list_view.setFont(font)
        self.online_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.online_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.online_list_view.setObjectName("online_list_view")
        self.onsite_list_view = QtWidgets.QListWidget(controll_ui)
        self.onsite_list_view.setGeometry(QtCore.QRect(140, 70, 161, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.onsite_list_view.setFont(font)
        self.onsite_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.onsite_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.onsite_list_view.setObjectName("onsite_list_view")

        self.retranslateUi(controll_ui)
        QtCore.QMetaObject.connectSlotsByName(controll_ui)

    def retranslateUi(self, controll_ui):
        _translate = QtCore.QCoreApplication.translate
        controll_ui.setWindowTitle(_translate("controll_ui", "Dialog"))
        self.btn_onsite_ready.setText(_translate("controll_ui", "Fertig zur Abholung"))
        self.btn_onsite_remove.setText(_translate("controll_ui", "Löschen"))
        self.btn_onsite_reset.setText(_translate("controll_ui", "Reset"))
        self.btn_online_ready.setText(_translate("controll_ui", "Fertig zur Abholung"))
        self.btn_online_reset.setText(_translate("controll_ui", "Reset"))
        self.btn_online_remove.setText(_translate("controll_ui", "Löschen"))
        self.label.setText(_translate("controll_ui", "Bestellung vor Ort/Phone "))
        self.label_2.setText(_translate("controll_ui", "Onlinebestellung"))
